# Generated by Django 3.1 on 2021-11-19 08:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('companyurl', models.URLField(verbose_name='Company URL')),
                ('location', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('is_current', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('company_image', models.CharField(blank=True, help_text='path to company image, local or otherwise', max_length=250)),
            ],
            options={
                'verbose_name_plural': '04. Jobs',
                'db_table': 'jobs',
                'ordering': ['-end_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '10. Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MesLanguageProgrammation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(5, 'Expert'), (4, 'Advanced'), (3, 'Intermediate'), (2, 'Novice'), (1, 'Fundamental Awareness')], default=1, help_text='Choice between 1 and 5')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': '11. Mes languages Programmation',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MesLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('level', models.IntegerField(choices=[(5, 'Native'), (4, 'Full professional proficiency'), (3, 'Professional working proficiency'), (2, 'Limited professional proficiency'), (1, 'Elementary professional proficiency')], default=5, help_text='Choice between 1 and 5')),
                ('addendum', models.CharField(blank=True, max_length=20)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.language')),
            ],
            options={
                'verbose_name_plural': 'Mes languages',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, help_text='e.g. PhD', max_length=255, null=True)),
                ('locality', models.CharField(blank=True, help_text='e.g. city such as Boston', max_length=255, null=True)),
                ('region', models.CharField(blank=True, help_text='e.g. MA or Italy', max_length=255, null=True)),
                ('title', models.CharField(blank=True, help_text='e.g. Developer', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('twittername', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/resume/img/')),
                ('cv_pdf', models.FileField(blank=True, help_text='Downloadable resume file', null=True, upload_to='static/resume/img/')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.ManyToManyField(related_name='mes_language', through='resume.MesLanguages', to='resume.Language')),
            ],
            options={
                'verbose_name_plural': '01. Personal Info',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': '08. Programming areas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': '12. ProjectTypes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': '06. Skillsets',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('skillurl', models.URLField(blank=True, null=True, verbose_name='Skill URL')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personalinfo')),
                ('skillset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_skills', to='resume.skillset')),
            ],
            options={
                'verbose_name_plural': '07. Skills',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authors', models.TextField()),
                ('author_underlined', models.CharField(default='Marin A', max_length=50)),
                ('journal', models.CharField(max_length=150)),
                ('year', models.IntegerField(default=2021)),
                ('order', models.IntegerField(default=1)),
                ('journalpages', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, verbose_name='Publication URL')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personalinfo')),
            ],
            options={
                'verbose_name_plural': '14. Publications',
                'db_table': 'publications',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, help_text='Text shown in project list')),
                ('long_description', models.TextField(blank=True, help_text='Text shown in modals appearing when clicking on images')),
                ('link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, help_text='Preferred width x height: 247x200', upload_to='static/resume/img/')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personalinfo')),
                ('projtype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.projecttype')),
            ],
            options={
                'verbose_name_plural': '12. Projects',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('programmingarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.programmingarea')),
            ],
            options={
                'verbose_name_plural': '09. Programming languages',
                'db_table': 'programminglanguage',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='programming_language',
            field=models.ManyToManyField(related_name='mes_programming_language', through='resume.MesLanguageProgrammation', to='resume.ProgrammingLanguage'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personalinfo')),
            ],
            options={
                'verbose_name_plural': '02. Overview',
            },
        ),
        migrations.AddField(
            model_name='meslanguages',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personalinfo'),
        ),
        migrations.AddField(
            model_name='meslanguageprogrammation',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personalinfo'),
        ),
        migrations.AddField(
            model_name='meslanguageprogrammation',
            name='programming_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.programminglanguage'),
        ),
        migrations.CreateModel(
            name='JobAccomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.job')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personalinfo')),
            ],
            options={
                'verbose_name_plural': '05. Job Accomplishments',
                'db_table': 'jobaccomplishment',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personalinfo'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name2', models.CharField(blank=True, max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('location2', models.CharField(blank=True, max_length=250)),
                ('schoolurl', models.URLField(blank=True, verbose_name='School URL')),
                ('schoolurl2', models.URLField(blank=True, verbose_name='School URL2')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('degree', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personalinfo')),
            ],
            options={
                'verbose_name_plural': '03. Education',
                'ordering': ['-end_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('achievement_pdf', models.FileField(blank=True, help_text='Downloadable file', upload_to='static/resume/img/')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personalinfo')),
            ],
            options={
                'verbose_name_plural': '13. Achievements',
                'db_table': 'achievement',
                'ordering': ['order', 'id'],
            },
        ),
    ]
